import nimjson
import json

# Generated by `nimjson obj.json -O:Obj >> main.nim`.
type
  Obj = ref object
    point: Point
    length: int64
    responseCode: string
    debugFlag: bool
    rectangles: seq[Rectangles]
  Point = ref object
    x: float64
    y: float64
  Rectangles = ref object
    width: int64
    height: int64

let repo = parseFile("obj.json").to(Obj)

echo repo[]
echo repo[].point[]
for rect in repo[].rectangles:
  echo rect[]
